### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Govinda-Fichtner** [iamteem/redisco#34]
I am getting the following ImportError. I am using Python 3.3.3 - before with Python 2.7.6 everything worked.

``` bash
Traceback (most recent call last):
  File "./run.py", line 3, in <module>
    from app import app
  File "/Users/govindaf/workspace/commander/commander/app/__init__.py", line 8, in <module>
    from app import views
  File "/Users/govindaf/workspace/commander/commander/app/views.py", line 7, in <module>
    from redisco import models, connection_setup
  File "/Users/govindaf/workspace/commander/commander/venv/lib/python3.3/site-packages/redisco/models/__init__.py", line 1, in <module>
    from base import *
ImportError: No module named 'base'
```

What is wrong here?

**Comment by jason-womack** [comment]
I am encountering a similar error with python 3.5.2.  Any resolution to this issue?

**Comment by Artawower** [comment]
same
